language: node_js
node_js:
  - "12.12"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm update
install:
  - npm ci
script:
  - npm run test
  - npm run coveralls
  - npm run build
